### ISSUE TITLE
c-\ conflict with default bindings undo.

### ISSUE THREAD

**Issue by snmsts** [nz-tcoder/cl-tcode#1]
潰しちゃいけないキーだと思うのですが。

**Comment by nz-tcoder** [comment]
setup-tcodeにモード切替のキーを指定し、問答無用にディフォルトキーバインディングを変えないようにした。
 0e6187cad8ba44ab26069a4cad38263060c1f177

**Comment by snmsts** [comment]
ありがとうございました。
